before:
  hooks:
    - go mod tidy

builds:
  - id: nps
    main: ./cmd/nps/nps.go
    binary: nps
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - loong64

  - id: npc
    main: ./cmd/npc/npc.go
    binary: npc
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - loong64

archives:
  - id: nps-archive
    builds:
      - nps
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - conf/nps.conf
      - conf/tasks.json
      - conf/clients.json
      - conf/hosts.json
      - conf/server.key
      - conf/server.pem
      - web/views
      - web/static

  - id: npc-archive
    builds:
      - npc
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - conf/npc.conf
      - conf/multi_account.conf

checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ incpatch .Version }}-next"